openapi: 3.0.3
info:
  title: User Service API
  description: API for the User service
  contact:
    email: helene.coullon@imt-atlantique.fr
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
tags:
- name: developers
  description: Operations available to developers
paths:
  /:
    get:
      tags:
      - developers
      summary: Home page of the service
      description: Returns the homepage of the service
      operationId: home
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: string
                example: "<h1 style='color:blue'>Welcome to the User service!</h1>"
  /users:
    get:
      tags:
      - developers
      summary: Get all users
      description: Returns a list of all users
      operationId: getUsers
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: John Doe
                    email:
                      type: string
                      example: john.doe@example.com
  /movies:
    get:
      tags:
      - developers
      summary: Get all movies
      description: Returns a list of all movies from the movies API
      operationId: getMovies
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: Inception
                    director:
                      type: string
                      example: Christopher Nolan
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Failed to fetch movies"
  /bookings/{user_id}:
    get:
      tags:
      - developers
      summary: Get bookings for a user
      description: Returns a list of bookings for a specific user
      operationId: getBookings
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: ID of the user
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                    example: 1
                  bookings:
                    type: array
                    items:
                      type: object
                      properties:
                        booking_id:
                          type: integer
                          example: 101
                        date:
                          type: string
                          example: "2023-10-01"
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not found"
  /moviesinfo/{user_id}:
    get:
      tags:
      - developers
      summary: Get movies info for a user
      description: Returns detailed movie information for a specific user's bookings
      operationId: getMoviesInfo
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          description: ID of the user
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: Inception
                    director:
                      type: string
                      example: Christopher Nolan
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "User not found"